"""
Centerline to Vessel Uncertainty Overlay Module

This module processes float centerline uncertainty maps (generated by test.py) and overlays them onto vessel segmentation
predictions (generated by segmentation_unet3d). It uses a nearest neighbor approach within vessel regions to propagate uncertainty
values from centerline points to all vessel voxels. This is to restore the vessel thickness.

The main functionality includes:
- Loading centerline uncertainty maps and vessel segmentation predictions
- Finding nearest centerline points for each vessel voxel within a 64x64x64 cube
- Checking connectivity paths between centerline points and vessel voxels
- Overlaying uncertainty values onto vessel regions
- Saving results in both .npy and .tiff formats
"""

import numpy as np 
import os, glob
import imageio.v3 as iio
from time import time
import json

# Load configuration parameters
with open('./config.json', 'r') as f:
    params = json.load(f)

# Directory paths from configuration
cl_dir = params['output_folder']  # Directory containing centerline uncertainty maps (float values)
vl_dir = params['npy_seg_dir']    # Directory containing vessel segmentation predictions (binary)
save_dir = cl_dir.replace("skel_uncertainty", "final_uncertainty")  # Output directory for final uncertainty maps

# Create output directory if it doesn't exist
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

# Define 26-connectivity neighborhood for 3D path checking
# This includes all 26 adjacent voxels in a 3x3x3 cube around a central voxel
neighbors_26 = [
    [i, j, k] for i in [-1,0,1] for j in [-1,0,1] for k in [-1,0,1]
    if not (i == 0 and j == 0 and k == 0)
]

def checkbounds(x, y, z, shape):
    """
    Check if 3D coordinates are within the bounds of a given shape.
    
    Args:
        x (int): X coordinate
        y (int): Y coordinate  
        z (int): Z coordinate
        shape (tuple): Shape of the 3D array (x_dim, y_dim, z_dim)
        
    Returns:
        bool: True if coordinates are within bounds, False otherwise
    """
    return 0 <= x < shape[0] and 0 <= y < shape[1] and 0 <= z < shape[2]

def check_path(init_npy, loc, target):
    """
    Check if there's a connected path between two points in a 3D binary image.
    
    This function creates a straight-line path between the source and target points
    and verifies that all voxels along this path have non-zero values (indicating
    they belong to the vessel structure). This ensures that the uncertainty of a neighboring vessel does not affect the uncertainty of the current vessel.
    
    Args:
        init_npy (numpy.ndarray): 3D binary image where 1 indicates vessel voxels
        loc (tuple): Source coordinates (x, y, z)
        target (tuple): Target coordinates (x, y, z)
        
    Returns:
        bool: True if a connected path exists, False otherwise
    """
    loc_x, loc_y, loc_z = loc
    target_x, target_y, target_z = target
    
    # Create linear interpolation paths for each dimension
    path_x = np.linspace(loc_x, target_x, num=abs(loc_x - target_x) + 1, dtype=int)
    path_y = np.linspace(loc_y, target_y, num=abs(loc_y - target_y) + 1, dtype=int)
    path_z = np.linspace(loc_z, target_z, num=abs(loc_z - target_z) + 1, dtype=int)
    
    # Check if all voxels along the path are vessel voxels (non-zero)
    for x, y, z in zip(path_x, path_y, path_z):
        if init_npy[x, y, z] == 0:
            return False
    return True

def overlay_nn_3d_withinvessel(init_npy, cl_npy):
    """
    Overlay centerline uncertainty values onto vessel voxels using nearest neighbor approach.
    
    For each vessel voxel, this function finds the nearest centerline point within a 64x64x64
    cube and assigns the centerline's uncertainty value to the vessel voxel, provided there's
    a connected path between them.
    
    Args:
        init_npy (numpy.ndarray): 3D vessel segmentation mask (binary: 0 or 1)
        cl_npy (numpy.ndarray): 3D centerline uncertainty map (float values in [0,1])
        
    Returns:
        numpy.ndarray: 3D uncertainty map with values overlaid onto vessel regions
    """
    # Initialize output array with zeros
    ol_npy = np.zeros_like(init_npy)
    
    # Find all centerline points (non-zero uncertainty values)
    nonzero_locs = np.argwhere(cl_npy > 0.)
    total_points = np.sum(init_npy == 1.)  # Total vessel voxels to process
    processed = 0
        
    # Get image dimensions
    nx, ny, nz = init_npy.shape
    radius = 32  # Half of 64^3 cube for local search
    
    # Process each vessel voxel
    for x, y, z in np.argwhere(init_npy == 1.):
        processed += 1
        if processed % 1000 == 0:
            print(f"Processing: {processed}/{total_points}")
            
        # Define bounds for the cubic search region around current voxel
        x_min = max(0, x - radius)
        x_max = min(nx, x + radius + 1)
        y_min = max(0, y - radius)
        y_max = min(ny, y + radius + 1)
        z_min = max(0, z - radius)
        z_max = min(nz, z + radius + 1)
        
        # Find centerline points within the cubic region
        mask = (
            (nonzero_locs[:, 0] >= x_min) & (nonzero_locs[:, 0] < x_max) &
            (nonzero_locs[:, 1] >= y_min) & (nonzero_locs[:, 1] < y_max) &
            (nonzero_locs[:, 2] >= z_min) & (nonzero_locs[:, 2] < z_max)
        )
        local_points = nonzero_locs[mask]
        
        # Skip if no centerline points found in local region
        if len(local_points) == 0:
            continue
            
        # Compute Euclidean distances to all local centerline points
        dists = np.sqrt(
            np.power(local_points[:, 0] - x, 2) +
            np.power(local_points[:, 1] - y, 2) +
            np.power(local_points[:, 2] - z, 2)
        )
        
        # Sort centerline points by distance (nearest first)
        sorted_indices = np.argsort(dists)
        local_points = local_points[sorted_indices]
        
        # Check connectivity paths in order of increasing distance
        # Assign uncertainty value from first connected centerline point found
        for loc in local_points:
            if check_path(init_npy, tuple(loc), (x, y, z)):
                ol_npy[x, y, z] = cl_npy[loc[0], loc[1], loc[2]]
                break
    
    return ol_npy

if __name__ == "__main__":
    """
    Main execution block for processing centerline uncertainty overlay.
    
    This script processes a list of test samples, loading both vessel segmentation
    predictions and centerline uncertainty maps, then overlays the uncertainty
    values onto the vessel regions and saves the results.
    """
        
    # Load list of test samples to process
    file_list = open("../test-samples.csv").readlines()
    sorted(file_list)
    
    # Process each sample in the test list
    for basename_ext in file_list:
        basename = basename_ext.split(".")[0]
        
        # Find vessel segmentation file (TIFF format)
        vl_file = glob.glob(os.path.join(vl_dir, f"*{basename}*tiff"))
        assert len(vl_file) == 1, "multiple files found"
        vl_file = vl_file[0]

        # Find centerline uncertainty file (NPY format)
        cl_file = glob.glob(os.path.join(cl_dir, f"*{basename}*npy"))
        assert len(cl_file) == 1, "multiple files found"
        cl_file = cl_file[0]

        # Define output file paths
        ol_file_npy = os.path.join(save_dir, f"{basename}_uncertainty.npy")   # NumPy format
        ol_file_tiff = os.path.join(save_dir, f"{basename}_uncertainty.tiff") # TIFF format

        test_start_time = time()
        
        # Load centerline uncertainty map from .npy file (values in [0,1] range)
        cl_npy = np.load(cl_file).astype(np.float32)
        
        # Load 3D vessel segmentation from TIFF file and normalize to [0,1] range
        vl_npy = iio.imread(vl_file).astype(np.float32)
        vl_npy = vl_npy / np.max(vl_npy)

        # Ensure both arrays have the same dimensions
        assert cl_npy.shape == vl_npy.shape, "shape mismatch"
        
        # Create initial mask combining centerline and vessel regions
        init_npy = np.where(cl_npy > 0, cl_npy, vl_npy)
        
        # Overlay centerline uncertainty onto vessel regions
        ol_npy = overlay_nn_3d_withinvessel(vl_npy, cl_npy)

        # Save results in both NumPy and TIFF formats
        np.save(ol_file_npy, ol_npy)
        iio.imwrite(ol_file_tiff, ol_npy)
        
        print(f"Saved as {ol_file_npy} and {ol_file_tiff}")

        test_end_time = time()
        print(f"Processing {basename} took {(test_end_time - test_start_time)/60:.2f} minutes")